# render.yaml - Simplified working configuration for Render
services:
  # Main Web Service
  - type: web
    name: dinari-testnet-api
    env: python3
    repo: https://github.com/EmekaIwuagwu/dinari-blockchain.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: NODE_ENV
        value: testnet
      - key: NODE_ID
        value: testnet_node_1
      - key: NODE_TYPE
        value: validator
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: BLOCKCHAIN_NETWORK
        value: testnet
      - key: CONTRACTS_ENABLED
        value: "true"
      - key: SUPPORTED_CURRENCIES
        value: "NGN,KES,ZAR,GHS,EGP,USD"
      - key: PORT
        value: "8545"

  # Background Worker (optional - comment out if not needed)
  # - type: worker
  #   name: dinari-testnet-worker
  #   env: python3
  #   repo: https://github.com/EmekaIwuagwu/dinari-blockchain.git
  #   branch: main
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: python tools/start_node.py
  #   plan: starter
  #   region: oregon

# Database
databases:
  - name: dinari-testnet-db
    databaseName: dinari_blockchain
    user: dinari
    plan: starter
    region: oregon